on:
  push:
    branches:
      - develop
      - stage
      - main
    tags:
      - 'release-*' # Triggers when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}"
      - name: Print a message
        run: echo "This is a message from my GitHub Actions job!"
      - name: Show runner OS
        run: echo "Running on ${{ runner.os }}"
      - name: Display repository details
        run: echo "Repository ${{ github.repository }}"

  deploy:
    runs-on: self-hosted
    steps:
    - run: echo "Repository ${{ github.repository }}"

  ManualApprove:
    needs: build
    environment: approvers
    runs-on: self-hosted
    steps:
    - name: manual approve
      run: echo "Manually approved"