name: CI/CD Pipeline

on:
  workflow_dispatch:
    - main
  push:
    branches:
      - develop


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print a message
        run: echo "This is a message from my GitHub Actions job!"
      - name: Show runner OS
        run: echo "Running on ${{ runner.os }}"
      - name: Display repository details
        run: echo "Repository ${{ github.repository }}"

  deploy:
    runs-on: self-hosted
    steps:
      - name: Print "Hello from depoy task"
        run: echo "Hello"
