on:
  push:
    branches:
      - develop
      - stage
      - main
    tags:
      - 'release-*' # Triggers when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}"
      - name: Print a message
        run: echo "This is a message from my GitHub Actions job!"
      - name: Show runner OS
        run: echo "Running on ${{ runner.os }}"
      - name: Display repository details
        run: echo "Repository ${{ github.repository }}"

  manual-approval:
    name: Manual Approval
    runs-on: self-hosted
    needs: build
    if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rudikrudik
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the d eployment."
          run: echo "${{ github.TOKEN }}"

  deploy:
    runs-on: self-hosted
    needs: manual-approval
    steps:
    - name: Manual approve
      run: echo "Repository ${{ github.repository }}"